import os

from src.constants.vars import (
    APP_VIEW_ROUTE_NAME,
    BLUEPRINT_NOTES_PATH,
    NOTES_BLUEPRINT_ROUTE_NAME,
    VIEW_APP_PATH,
)


class DefaultConfig:
    TZ = os.getenv("TZ", "America/Argentina/Buenos_Aires")

    SECRET_KEY = os.getenv("SECRET_KEY", "supersecret")
    HOST = os.getenv("HOST", "0.0.0.0")
    PORT = int(os.getenv("PORT", 5000))

    MYSQL_HOST = os.getenv("MYSQL_HOST")
    MYSQL_USER = os.getenv("MYSQL_USER")
    MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
    MYSQL_PORT = os.getenv("MYSQL_PORT", 3306)
    MYSQL_DB_NAME = os.getenv("MYSQL_DB_NAME")
    SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DB_NAME}"

    SQLALCHEMY_TRACK_MODIFICATIONS = False

    GET_ALL_NOTES_ROUTE = f"{NOTES_BLUEPRINT_ROUTE_NAME}.get_all"
    CREATE_NOTE_ROUTE = f"{NOTES_BLUEPRINT_ROUTE_NAME}.create"
    DELETE_NOTE_ROUTE = f"{NOTES_BLUEPRINT_ROUTE_NAME}.delete"
    EDIT_NOTE_ROUTE = f"{NOTES_BLUEPRINT_ROUTE_NAME}.edit"

    GET_ALL_NOTES_ROUTE_PATH = BLUEPRINT_NOTES_PATH
    CREATE_NOTE_ROUTE_PATH = BLUEPRINT_NOTES_PATH
    DELETE_NOTE_ROUTE_PATH = f"{BLUEPRINT_NOTES_PATH}/<id>"
    EDIT_NOTE_ROUTE_PATH = f"{BLUEPRINT_NOTES_PATH}/<id>"

    HOME_VIEW = f"{APP_VIEW_ROUTE_NAME}.home"
    HOME_VIEW_PATH = f"{VIEW_APP_PATH}/home"

    DEBUG = False
    TESTING = False
