# ##### FLASH #####
FLASH_SUCCESS = "success"
FLASH_ERROR = "error"

# ##### SUCCESS #####
CODE_SUCCESS_GET_ALL_NOTES = "SUCCESS_GET_ALL_NOTES"
CODE_SUCCESS_ADD_NOTE = "SUCCESS_ADD_NOTE"
CODE_SUCCESS_DELETE_NOTE = "SUCCESS_DELETE_NOTE"
CODE_SUCCESS_EDIT_NOTE = "SUCCESS_EDIT_NOTE"

# ##### ERROR #####
CODE_ERROR_INTERNAL_SERVER = "ERROR_INTERNAL_SERVER"
CODE_ERROR_DATABASE = "ERROR_DATABASE"
CODE_ERROR_GENERIC = "ERROR_GENERIC"

# ##### NOT_VALID #####
CODE_NOT_VALID_INTEGER = "NOT_VALID_INTEGER"
CODE_NOT_VALID_FIELDS = "NOT_VALID_FIELDS"

# ##### NOT_EXISTS #####

# ##### ALREADY_EXISTS #####
CODE_ALREADY_EXISTS_NOTE = "ALREADY_EXISTS_NOTE"

# ##### NOT_FOUND #####
CODE_NOT_FOUND_NOTE = "NOT_FOUND_NOTE"
