import os
from pathlib import Path

from src.constants.vars import (
    APP_TEMPLATES_FOLDER_NAME,
    CSS_FOLDER_NAME,
    GENERAL_TEMPLATES_FOLDER_NAME,
    JS_FOLDER_NAME,
    STATIC_FOLDER_NAME,
    TEMPLATE_HOME_NAME,
    TS_FOLDER_NAME,
    VERSION_VIEWS,
)

ROOT_PATH = Path(__file__).parent.parent.parent

SRC_PATH = os.path.join(ROOT_PATH, "src")

JS_FOLDER_PATH = os.path.join(SRC_PATH, STATIC_FOLDER_NAME, JS_FOLDER_NAME)
TS_FOLDER_PATH = os.path.join(SRC_PATH, STATIC_FOLDER_NAME, TS_FOLDER_NAME)
CSS_FOLDER_PATH = os.path.join(SRC_PATH, STATIC_FOLDER_NAME, CSS_FOLDER_NAME)

GENERAL_TEMPLATES_FOLDER_PATH = os.path.join(SRC_PATH, VERSION_VIEWS, GENERAL_TEMPLATES_FOLDER_NAME)
APP_TEMPLATES_FOLDER_PATH = os.path.join(SRC_PATH, GENERAL_TEMPLATES_FOLDER_NAME, VERSION_VIEWS, APP_TEMPLATES_FOLDER_NAME)

RENDER_TEMPLATE_HOME_PATH = os.path.join(VERSION_VIEWS, APP_TEMPLATES_FOLDER_NAME, TEMPLATE_HOME_NAME)

GENERAL_FILES_PATH = os.path.join(GENERAL_TEMPLATES_FOLDER_PATH, "*.html")
GENERAL_FILES_PATH_2 = os.path.join(GENERAL_TEMPLATES_FOLDER_PATH, "**", "*", "*.html")
APP_FILES_PATH = os.path.join(APP_TEMPLATES_FOLDER_PATH, "*.html")
APP_FILES_PATH_2 = os.path.join(APP_TEMPLATES_FOLDER_PATH, "**", "*", "*.html")
JS_FILES_PATH = os.path.join(JS_FOLDER_PATH, "*.js")
JS_FILES_PATH_2 = os.path.join(JS_FOLDER_PATH, "**", "*", "*.js")
CSS_FILES_PATH = os.path.join(CSS_FOLDER_PATH, "*.css")
CSS_FILES_PATH_2 = os.path.join(CSS_FOLDER_PATH, "**", "*.css")
TS_FILES_PATH = os.path.join(TS_FOLDER_PATH, "*.ts")
TS_FILES_PATH_2 = os.path.join(TS_FOLDER_PATH, "**", "*", "*.ts")
