# FOLDER NAMES
STATIC_FOLDER_NAME = "static"

JS_FOLDER_NAME = "js"
TS_FOLDER_NAME = "ts"
CSS_FOLDER_NAME = "css"

GENERAL_TEMPLATES_FOLDER_NAME = "templates"
APP_TEMPLATES_FOLDER_NAME = "app"

# VERSIONS
VERSION_VIEWS = "v1"
VERSION_BLUEPRINTS = "v1"

# ROUTE NAMES
NOTES_BLUEPRINT_ROUTE_NAME = "notes"
APP_VIEW_ROUTE_NAME = "app_view"

# BLUEPRINTS PATHS
PREFIX_BLUEPRINTS_PATH = f"/api/{VERSION_BLUEPRINTS}"
BLUEPRINT_NOTES_PATH = f"{PREFIX_BLUEPRINTS_PATH}/notes"

PREFIX_VIEWS_PATH = f"/views/{VERSION_VIEWS}"
VIEW_APP_PATH = f"{PREFIX_VIEWS_PATH}/app"

# TEMPLATE NAMES
TEMPLATE_HOME_NAME = "home.html"
